### ISSUE TITLE
Packer-Templates - Packer Build - Failed to retrieve the pre-configuration file

### ISSUE THREAD

**Issue by Siya360** [udacity/devops-intro-project#106]
Hi, when trying to build a box with Packer, it first stalls at "==> virtualbox-iso: Waiting for SSH to become available..."; I believe it's running preseed configs in the background. An hour later, it displays the error: "Failed to retrieve the reconfiguration file. The file needed for reconfiguration could not be retrieved from HTTP://10.0.2.2:8029/preseed.cfg. The installation will proceed in non-automated mode. <continue>

Please advise of a valid URL for the preseed file, or the work around this huddle.

**Comment by nickfourtimes** [comment]
Came here looking for info on this exact same problem! Seems like some part of the configuration is out of date...
