### ISSUE TITLE
Unable to find local grunt

### ISSUE THREAD

**Issue by maxim-pandra** [udacity/devops-intro-project#18]
got this message when tried to perforem "grunt -v"

**Comment by TheMonolithX64** [comment]
Need to re-run `sudo npm install` within vagrant `/devops-kungfu` directory

**Comment by 13rac1** [comment]
https://stackoverflow.com/questions/13925916/what-is-causing-this-error-fatal-error-unable-to-find-local-grunt Should solve this issue.
