### ISSUE TITLE
Use of latest packages and distros in the build config

### ISSUE THREAD

**Issue by vharsh** [udacity/devops-intro-project#20]
I see the configuration has 
- Ubuntu 14.04 
- Node 0.10.something ( support expires this October )
  Both of which will not be supported after some time.

1 > Why is the script not using Ubuntu 16.04?

Moreover I saw an eye-poping line, isn't that too much space, for a basic vm-image?

```
    virtualbox-iso: 7374503936 bytes (7.4 GB) copied, 18.8767 s, 391 MB/s
```

**Comment by 13rac1** [comment]
> Why is the script not using Ubuntu 16.04?

It is being upgraded in #78
