### ISSUE TITLE
Unable to install packer and set variable

### ISSUE THREAD

**Issue by sjfaisal** [udacity/devops-intro-project#21]
I am trying to install packer on my machine but its says , no command packer found.
I was successfully able to unzip it ,but i am getting tough time to set an variable path.

can you please guide me how to set a variable. the packer is installed at" /home/ubuntu" location.

thanks

**Comment by loide** [comment]
Hi!
You just need add it to your PATH variable.
export PATH=$PATH:/path/to/packer

**Comment by 13rac1** [comment]
@sahiljuneja in Ubuntu 18.04 you can also just `sudo apt install packer`, but @loide is correct too.
