### ISSUE TITLE
packer build

### ISSUE THREAD

**Issue by JoaoPedroFerreira** [udacity/devops-intro-project#24]
=> Builds finished but no artifacts were created.
jferreira@jferreira-VirtualBox ~/git/devops-intro-project-1/packer-templates $ packer build -only=virtualbox-iso application-server.json 
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso
==> virtualbox-iso: Starting HTTP server on port 8513
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 4279)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm ubuntu-14.04.4-server-amd64 --memory 512
    virtualbox-iso: Executing: modifyvm ubuntu-14.04.4-server-amd64 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
**==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: Could not launch a process for the machine 'ubuntu-14.04.4-server-amd64' (VERR_FILE_NOT_FOUND)
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage: error: Could not launch a process for the machine 'ubuntu-14.04.4-server-amd64' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp**

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: Could not launch a process for the machine 'ubuntu-14.04.4-server-amd64' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp

==> Builds finished but no artifacts were created.

I've this error . any ideas?

**Comment by hmaciasc** [comment]
Ubuntu 14.04.4 version has been replaced with 14.04.5, therefore change name and sha2 lines in file application-server.iso to continue.

 Line 4     "PACKER_BOX_NAME": "ubuntu-14.04.5-server-amd64",
 Line 42       "iso_checksum": "dde07d37647a1d2d9247e33f14e91acb10445a97578384896b4e1d985f754cc1",


Hope it helps.

**Comment by JasonDHubbard** [comment]
@hmaciasc 

I changed the lines as per your suggestion. It did get me a bit further, but I've now run into the following error. Any suggestions?

***********************************************************************************************************
***********************************************************************************************************

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/trusty/ubuntu-14.04.5-server-amd64.iso
==> virtualbox-iso: Starting HTTP server on port 8553
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3810)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm ubuntu-14.04.5-server-amd64 --memory 1024
    virtualbox-iso: Executing: modifyvm ubuntu-14.04.5-server-amd64 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'ubuntu-14.04.5-server-amd64' has terminated unexpectedly during startup with exit code 255 (0xff)
==> virtualbox-iso: VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'ubuntu-14.04.5-server-amd64' has terminated unexpectedly during startup with exit code 255 (0xff)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage.exe: error: The virtual machine 'ubuntu-14.04.5-server-amd64' has terminated unexpectedly during startup with exit code 255 (0xff)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

==> Builds finished but no artifacts were created.

***********************************************************************************************************
***********************************************************************************************************

**Comment by hmaciasc** [comment]
Looks like your VM is broken, I would try deleting it and downloading a fresh one running the same command. It worked for me anyways.

**Comment by RomelTorres** [comment]
After changing the name and the sha it downloads but it does not build anymore:

**==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'ubuntu-14.04.5-server-amd64' has terminated unexpectedly during startup because of signal 6
==> virtualbox-iso: VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage: error: The virtual machine 'ubuntu-14.04.5-server-amd64' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine**

Coudl anyone give me a hand?

**Comment by 13rac1** [comment]
This question is very old, but I'll answer anyway: Delete the VM entirely and start over.
