### ISSUE TITLE
What is vagrant login?

### ISSUE THREAD

**Issue by saadshahd** [udacity/devops-intro-project#4]
![untitled-1](https://cloud.githubusercontent.com/assets/5410903/10561681/8ce137dc-7535-11e5-8d1d-7f8ccab71d37.jpg)

**Comment by ynvtlmr** [comment]
You have to use the private-key.
On Windows, you'd have to use PuTTY, which gets a tad tricky...

Your key is located at: C:\Users\ytalmor\Videos\udacity\devops-intro-project\packer-templates\virtualbox\.vagrant\machines\default\virtualbox

Using this key, follow the instructions at: https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Connect-to-Your-Vagrant-Virtual-Machine-with-PuTTY

**Comment by simplydallas** [comment]
If you are using a general ssh.exe file in windows and it is in your path then all you should need to do is type 'Vagrant ssh' after typing 'vagrant up' in that folder and vagrants should handle the rest.  It looks like @ynvtlmr's answer makes sense here if you are using PuTTy.
