### ISSUE TITLE
New address for the Ubuntu iso

### ISSUE THREAD

**Issue by claclacla** [udacity/devops-intro-project#42]
I would like to share the new address for the Ubuntu version used on this project:
[http://old-releases.ubuntu.com/releases/14.04.4/ubuntu-14.04.4-server-amd64.iso](url)  

Write it on application-server.json file as "iso_url" value.

Hope it helps anyone who has my same error with the checksum after running the "packer build" command.

Hi,
Simone

**Comment by sdmunozsierra** [comment]
Thank you @claclacla I had to change the address for the iso as well.

**Comment by lurden** [comment]
well i changed the release to 14.04.5 :)
"PACKER_BOX_NAME": "ubuntu-14.04.5-server-amd64"

**Comment by lurden** [comment]
and the iso_checksum as well :)
"iso_checksum": "dde07d37647a1d2d9247e33f14e91acb10445a97578384896b4e1d985f754cc1",

**Comment by sanghapriya** [comment]
changing PACKER_BOX_NAME and iso_checksum worked for me.Thanks.

**Comment by 13rac1** [comment]
Fixed first by #28, although I merged #76 due to completeness.
