### ISSUE TITLE
vagrant box add producing error

### ISSUE THREAD

**Issue by spkesan** [udacity/devops-intro-project#51]
"vagrant box add ubuntu-14.04.4-server-amd64-appserver_virtualbox.box --name devops-appserver" producing the following error.

==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'devops-appserver' (v0) for provider: 
    box: Downloading: ubuntu-14.04.4-server-amd64-appserver_virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Also, after installing ubuntu in Virtualbox, when i shutdown the VM, the terminal still shows the following:

virtualbox-iso output will be in this color.

==> virtualbox-iso: Cannot find "Default Guest Additions ISO" in vboxmanage output (or it is empty)
==> virtualbox-iso: Downloading or copying Guest additions checksums
    virtualbox-iso: Downloading or copying: http://download.virtualbox.org/virtualbox/5.1.28/SHA256SUMS
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: http://download.virtualbox.org/virtualbox/5.1.28/VBoxGuestAdditions_5.1.28.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://old-releases.ubuntu.com/releases/14.04.4/ubuntu-14.04.4-server-amd64.iso
==> virtualbox-iso: Starting HTTP server on port 8939
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3456)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm ubuntu-14.04.4-server-amd64 --memory 1024
    virtualbox-iso: Executing: modifyvm ubuntu-14.04.4-server-amd64 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available..

**Comment by spkesan** [comment]
Found the solution:

make "headless" : false; in application-server.json
and during the installation mark "OpenSSH" package.

**Comment by ashish049** [comment]
@spkesan I am getting the same error in Vagrant box add command. I am not getting any artifacts saved in virtual box directory. Packer command ran fine for me, and didn't show any artifact related errors. Please help.
