### ISSUE TITLE
[SOLVED] Cannot find VBoxGuestAdditions.iso (Windows 10)

### ISSUE THREAD

**Issue by rothschild86** [udacity/devops-intro-project#52]
Verified the file was in the correct place within Vbox install, but no luck. Finally resolved by introducing the following line into the app-server script:

"guest_additions_url": "http://download.virtualbox.org/virtualbox/5.1.30/VBoxGuestAdditions_5.1.30.iso",

Note, that you might need to adjust to match the vbox version on your system.

**Comment by sisprotec** [comment]
Thank You....(~;)

**Comment by asozaev** [comment]
It works, thank you.

**Comment by AghaAsadKhan** [comment]
It Works, thank You.

**Comment by 13rac1** [comment]
Closing solved issue.

**Comment by bennylangston1** [comment]
WHAT IS DE PATH TO 
 into the app-server script:
