### ISSUE TITLE
packer build -only=virtualbox-iso application-server.json

### ISSUE THREAD

**Issue by vikasgubbi** [udacity/devops-intro-project#55]
packer build -only=virtualbox-iso application-server.json  on centos 7 bare metal machine.

command running more than 6 hrs with no error message or output.

how long it take to get the output.

do i need to do any custom modify to application-server.json file.  please advice

**Comment by internetstyle** [comment]
+1

**Comment by vikasgubbi** [comment]
+1 means

**Comment by duoarc** [comment]
Any solution to this issue @vikasgubbi
