### ISSUE TITLE
Packer download ISO error

### ISSUE THREAD

**Issue by wyichew2708** [udacity/devops-intro-project#56]
Can refer to http://download.virtualbox.org/virtualbox/ and http://releases.ubuntu.com/trusty/

Modify the application-server.json code according to your virtualbox version, latest ubuntu version and SHA256SUMS.

examples:
`        "guest_additions_path": "VBoxGuestAdditions_5.2.2.iso",
		"guest_additions_url": "http://download.virtualbox.org/virtualbox/5.2.2/VBoxGuestAdditions_5.2.2.iso",
        "guest_os_type": "Ubuntu_64",
        "http_directory": "http",
        "iso_checksum": "8317a0479a94877829b20a19df8a7c09187b31eecb3f1ed9d2b8cb8681a81bb8",
"iso_checksum": "dde07d37647a1d2d9247e33f14e91acb10445a97578384896b4e1d985f754cc1",
        "iso_checksum_type": "sha256",
        "iso_url": "http://releases.ubuntu.com/trusty/{{ user `PACKER_BOX_NAME` }}.iso",
`

**Comment by 13rac1** [comment]
Fixed by #76
