### ISSUE TITLE
 Failed to parse template: open application-server.json:

### ISSUE THREAD

**Issue by fhagi** [udacity/devops-intro-project#57]
Hi there,

I keep getting Failed to parse template, the application-server.json is there and I ran the command under Home@Home-PC MINGW64 /c/Program Files/Packer and also added pakers path to environment variable
and all the other executables as well.

Home@Home-PC MINGW64 /c/Program Files/Packer
$ packer build -only=virtualbox-iso application-server.json Failed to parse template: open application-server.json: The system cannot find the file specified.

I am logged-in as Administrator and folder has full access.

Any suggestions would be appreciated!

**Comment by ndsubhash** [comment]
Did you try running this command from the 'devops/packer-templates' folder.

**Comment by 13rac1** [comment]
No reply to question from OP. Closing.
