### ISSUE TITLE
virtualbox-iso: ISO download failed. Build 'virtualbox-iso' errored: ISO download failed.

### ISSUE THREAD

**Issue by minnjm** [udacity/devops-intro-project#58]
run packer command on Windows 10:
packer build -only=virtualbox-iso application-server.json

got the following error:

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: 07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.

See the similiar issues were raised and fixed before. It now resurfaces because of new release, 14.04.05?

**Comment by minnjm** [comment]
Read through "Pull request" and saw that the version and checksum were updated to 14.04.5. I just forked the code today and it is still 14.04.4. Where I can download the latest and greatest, or the fixes have not been committed?

**Comment by oquirozm** [comment]
Just for the record:
Change the application-server.json file so in "PACKER_BOX_NAME" reads "ubuntu-14.04.5-server-amd64" and set the new checksum (dde07d37647a1d2d9247e33f14e91acb10445a97578384896b4e1d985f754cc1) at the "iso_checksum" property.

**Comment by ndsubhash** [comment]
Can I modify my local application-server.json file to reflect the 17.10 (artful) version? I guess I need to then change iso_url, packer_box_name and checksum

**Comment by oquirozm** [comment]
@ndsubhash probably, though, some setting or package in the box could get you an error for moving from 14.x to 17.x. Usually, major version change mean backward compatibility issues.

**Comment by ashish049** [comment]
I am getting the same error. I forked the code today only. I am totally new to Git and also installed the same today only and stuck with this issue. Please advise how this was resolved.

**Comment by oquirozm** [comment]
@ashish049 so look for the `application-server.json` file. In that file, look for the line that has the **PACKER_BOX_NAME** property. After the colon next to it, change the name of the packer box being used (add the version I wrote in my previous comment above). Update the `iso_checksum` property too. Got it?

**Comment by oquirozm** [comment]
@ashish049 awesome, glad to have been of help!

**Comment by 13rac1** [comment]
Fixed by #76

**Comment by margbogd** [comment]
Hello,

I have the same issue as @minnjm and I follow your instructions @oquirozm, but inside my templates folder does not exist any file named application-server.json....
Any help ?
