### ISSUE TITLE
Jenkins issue on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by ronyblum** [udacity/devops-intro-project#65]
Hi,

It seems that Jenkins is not installed properly due to dos2unix not running properly on the install_jenkins_plugins.sh script.
After debugging, seems dos2unix is not installed.

I added apt-get dos2unix it it works fine

**Comment by CodeWithOz** [comment]
@ronyblum I seem to have come upon this same problem. On what line of install_jenkins_plugins.sh did you add `apt-get dos2unix` for it to work?

**Comment by CodeWithOz** [comment]
Never mind. I got it to work by adding
```
# install dos2unix
sudo apt-get install dos2unix
```
after these lines 👇 
```
apt-get update
apt-get install -y jenkins
apt-get upgrade
```
Thanks for pointing out this problem.
