### ISSUE TITLE
Packer Build Issue

### ISSUE THREAD

**Issue by lavanya03mandarapu** [udacity/devops-intro-project#68]
Last login: Fri Aug 17 13:18:10 on ttys001
sreedhars-MacBook-Pro:~ sreedharailu$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin
sreedhars-MacBook-Pro:~ sreedharailu$ packer build -only=virtualbox-iso application-server.json
-bash: packer: command not found
sreedhars-MacBook-Pro:~ sreedharailu$ 

I would like to know how to exactly set path in Mac as the packer is downloaded through binary in my downloads. 

Thank you.

**Comment by Barathwaja** [comment]
Please refer this [Link](https://www.packer.io/intro/getting-started/install.html#precompiled-binaries). And change the packer_box_name referenced issue #74 as well.

**Comment by 13rac1** [comment]
@Barathwaja is correct. Closing.
