### ISSUE TITLE
Unable to install Grunt

### ISSUE THREAD

**Issue by ricardo-numakura** [udacity/devops-intro-project#70]
I tried running the command `grunt -v`, but couldn't, saying it was unable to locate local grunt. I tried installing it manually, but it returns the following error. 

![image](https://user-images.githubusercontent.com/14101238/44636588-20267000-a983-11e8-9f50-55282b1369b6.png)

Here's the npm debug log.

[npm-debug.log](https://github.com/udacity/devops-intro-project/files/2322146/npm-debug.log)

Can anyone help?

**Comment by PauloJFCabral** [comment]
I have the same problem

**Comment by 13rac1** [comment]
https://stackoverflow.com/questions/13925916/what-is-causing-this-error-fatal-error-unable-to-find-local-grunt Should solve this issue.
