### ISSUE TITLE
google compute  problem

### ISSUE THREAD

**Issue by ali-ok** [udacity/devops-intro-project#77]
hello  friends...  ı need a  help..  ı cant use  packer.   ı  got  the  fault  below..

please help...

ALİ-OKUMUŞ@ALI-OKUMUS MINGW64 ~/devops/packer-templates (master)
$ ls
account.json  application-server.json  control-server.json  http/  packer_cache/  scripts/  virtualbox/

ALİ-OKUMUŞ@ALI-OKUMUS MINGW64 ~/devops/packer-templates (master)
$ packer build -only=googlecompute application-server.json
googlecompute output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Using image: ubuntu-1404-trusty-v20150316
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-central1-a
==> googlecompute: Error creating instance: googleapi: Error 403: Required 'compute.zones.get' permission for 'projects/devops-228813/zones/us-central1-a', forbidden
Build 'googlecompute' errored: Error creating instance: googleapi: Error 403: Required 'compute.zones.get' permission for 'projects/devops-228813/zones/us-central1-a', forbidden

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Error creating instance: googleapi: Error 403: Required 'compute.zones.get' permission for 'projects/devops-228813/zones/us-central1-a', forbidden

==> Builds finished but no artifacts were created.

**Comment by 13rac1** [comment]
This should help you get started solving the problem: https://stackoverflow.com/questions/48232189/google-compute-engine-required-compute-zones-get-permission-error
