### ISSUE TITLE
Failed to parse template: open appilcation-server.json: The system cannot find the file specified.

### ISSUE THREAD

**Issue by HaychB** [udacity/devops-intro-project#80]
Has anyone found why this isn't working?

I've tried running:

`packer build -only=virtualbox-iso appilcation-server.json
`
Inside the directory that the JSON is installed. however I keep getting Parse error.

`Failed to parse template: open appilcation-server.json: The system cannot find the file specified.`

Any ideas would be appreciated.

**Comment by 13rac1** [comment]
You've transposed the characters in the name of the file, it is `application-server.json`. Is that the problem?

**Comment by 13rac1** [comment]
No Reply. Closing.
