### ISSUE TITLE
bash: cd: packer-templates: No such file or directory

### ISSUE THREAD

**Issue by waynedou1** [udacity/devops-intro-project#92]
Hi, I receive the following error:
wayne@main MINGW64 ~
$ cd packer-templates
bash: cd: packer-templates: No such file or directory

Please assist. Thank you in advance.

Below is a copy of the git clone command for reference: 

wayne@main MINGW64 ~
$ git clone http://github.com/waynedou1/devops-intro-project devops             Cloning into 'devops'...
warning: redirecting to https://github.com/waynedou1/devops-intro-project/
remote: Enumerating objects: 206, done.
remote: Total 206 (delta 0), reused 0 (delta 0), pack-reused 206
Receiving objects:  65% (134/206)
Receiving objects: 100% (206/206), 41.36 KiB | 536.00 KiB/s, done.
Resolving deltas: 100% (105/105), done.

**Comment by 13rac1** [comment]
You need to move into the `devops-intro-project` directory.
```
cd devops-intro-project
cd packer-templates
```
